(use-modules
 (srfi srfi-1)

 (gnu home)
 (guix channels)         

 (gnu services)
 (gnu home services)
 (gnu home services ssh)
 (gnu home services guix)
 (gnu home services gnupg)
 (gnu home services shells)
 (gnu home services desktop)
  
 (gnu packages emacs)
 (gnu packages emacs-xyz)
 (gnu packages gnuzilla)
 (gnu packages screen)
 (gnu packages terminals)
 (gnu packages vim)
 (gnu packages admin)
 (gnu packages tmux)
 (gnu packages gnome)
 (gnu packages polkit)
 (gnu packages compression)
 (gnu packages curl)
 (gnu packages version-control)
 (gnu packages ssh)
 (guix gexp)
 (guix inferior)
 
 (gnu packages wm)           
 (gnu packages xdisorg)      
 (gnu packages fonts)

 (gnu packages image)      
 (gnu packages music)      
 (gnu packages pulseaudio) 
 (gnu packages linux)      

 (gnu packages gl)

 (gnu packages uml)
 (gnu packages gnupg)
 (gnu packages tree-sitter)
 (gnu packages password-utils)
 
 (nongnu packages mozilla))

(define nonguix-pinned-channel
  (append
   (list (channel
	  (name 'nonguix)
	  (url "https://gitlab.com/nonguix/nonguix")
	  (commit "53c477b3e0a45b3bd0036647ac805a8f5e8f71d0")
	  ;; Fixes the warning: Authenticates the channel
	  (introduction
	   (make-channel-introduction
	    "897c1a470da759236cc11798f4e0a5f7d4d59fbc"
	    (openpgp-fingerprint
	     "2A39 3FFF 68F4 EF7A 3D29  12AF 6F51 20A0 22FB B2D5")))))
   ;; Fixes the error: Adds the required core 'guix' channel
   %default-channels))

(define firefox-pinned
  (first
   (lookup-inferior-packages
    (inferior-for-channels nonguix-pinned-channel)
    "firefox")))

(define my-emacs-packages
  (list
   emacs-pgtk
   emacs-gcmh
   emacs-use-package
   emacs-doom-themes
   emacs-doom-modeline
   emacs-all-the-icons
   emacs-almost-mono-themes
   emacs-tao-theme
   emacs-ef-themes
   emacs-which-key
   emacs-vertico
   emacs-orderless
   emacs-marginalia
   emacs-consult
   emacs-embark
   emacs-corfu
   emacs-org-roam
   emacs-consult-org-roam
   emacs-evil-org
   emacs-magit
   emacs-flymake-flycheck
   emacs-eglot
   emacs-eldoc-box
   emacs-smartparens
   emacs-yasnippet
   emacs-yasnippet-snippets
   emacs-plantuml-mode
   emacs-jsdoc
   emacs-evil
   emacs-evil-leader
   emacs-evil-commentary

   ;; Guix development
   emacs-guix
   emacs-geiser
   emacs-geiser-guile
   
   ;; Treesitter Grammars
   tree-sitter-python
   tree-sitter-go
   tree-sitter-javascript
   tree-sitter-typescript
   tree-sitter-json
   tree-sitter-bash))

;; 2. The Generated "Glue" Config
(define guix-emacs-config
  (mixed-text-file "guix-config.el"
		   ";; This file is generated by Guix. Do not edit.\n"
		   
		   ;; Disable 'ensure' because we cannot write to the store
		   "(setq use-package-always-ensure nil)\n"
		   
		   ;; Define the path to PlantUML Jar (Magic happens here!)
		   "(defvar guix-plantuml-jar-path \"" 
		   (file-append plantuml "/share/java/plantuml.jar") 
		   "\")\n"))

(home-environment
 (packages 
  (append (list
	   unzip
	   firefox
	   mesa 
	   vim
	   tmux
	   htop
	   curl

	   sway
	   swaylock
	   swayidle
	   waybar      
	   wofi        
	   foot
	   wl-clipboard
	   grim

	   pulseaudio    
	   playerctl     
	   brightnessctl 

	   polkit-gnome
	   font-awesome
	   font-dejavu             
	   font-google-noto
	   font-jetbrains-mono 
	   font-google-noto              
	   font-google-noto-emoji
	   network-manager-applet
	   adwaita-icon-theme
	   hicolor-icon-theme      
	   adwaita-icon-theme      
	   gnome-themes-extra      
	   gsettings-desktop-schemas

	   gnupg
	   password-store
	   pinentry-gnome3
	   openssh
	   git)
	  my-emacs-packages))

 (services
  (append
   (list
    (service home-bash-service-type
	     (home-bash-configuration
	      (guix-defaults? #t)
	      (bashrc 
	       (list 
		(plain-file "gpg-agent-setup" 
			    (string-append
			     "export GPG_TTY=$(tty)\n"
			     "gpg-connect-agent updatestartuptty /bye >/dev/null 2>&1\n"))))))

    (service home-gpg-agent-service-type
	     (home-gpg-agent-configuration
	      (pinentry-program 
	       (file-append pinentry-gnome3 "/bin/pinentry"))
	      
	      (default-cache-ttl 7200)
	      (max-cache-ttl 7200)  
	      
	      (ssh-support? #t)
	      
	      (extra-content "no-grab\n")))

    (service home-openssh-service-type
	     (home-openssh-configuration))

    (simple-service 'guix-emacs-config
		    home-files-service-type
		    (list `(".emacs.d/guix-config.el" ,guix-emacs-config)))

    (simple-service 'wayland-env-vars-service
		    home-environment-variables-service-type
		    `(("MOZ_ENABLE_WAYLAND" . "1")      
		      ("XDG_CURRENT_DESKTOP" . "sway")  
		      ("XDG_SESSION_TYPE" . "wayland")))

    (simple-service 'dotfiles
		    home-files-service-type
		    (list 
		     `(".config/waybar/config" ,(local-file "waybar/config"))
		     `(".config/waybar/style.css" ,(local-file "waybar/style.css"))
		     `(".config/waybar/scripts/weather.sh" ,(local-file "waybar/scripts/weather.sh"))
		     `(".config/wofi/style.css" ,(local-file "wofi/style.css"))
		     `(".tmux.conf" ,(local-file "tmux/tmux.conf"))
		     `(".emacs.d/init.el" ,(local-file "emacs/init.el"))
		     `(".config/foot/foot.ini" ,(local-file "foot/foot.ini"))
		     `(".config/sway/config" ,(local-file "sway/sway.conf"))
		     `(".gtkrc-2.0" ,(local-file "gtk/gtkrc-2.0"))
		     `(".config/gtk-3.0/settings.ini" ,(local-file "gtk/gtk3.ini"))
		     `(".config/gtk-4.0/settings.ini" ,(local-file "gtk/gtk4.ini"))))
    
    (service home-channels-service-type
	     (append
	      (list (channel
		     (name 'nonguix)
		     (url "https://gitlab.com/nonguix/nonguix")
		     (introduction
		      (make-channel-introduction
		       "897c1a470da759236cc11798f4e0a5f7d4d59fbc"
		       (openpgp-fingerprint
			"2A39 3FFF 68F4 EF7A 3D29  12AF 6F51 20A0 22FB B2D5")))))
	      %default-channels))))))
