;; Los módulos propios ((my-packages ...), (my-scripts ...)) viven en
;; guix-packages/ dentro de este mismo repo, así que la ruta se deriva del
;; fichero: no hay copia que sincronizar en $HOME ni ruta absoluta que romper
;; si el repo se mueve.
(add-to-load-path
 (string-append (dirname (canonicalize-path (current-filename))) "/guix-packages"))

(use-modules
 (srfi srfi-1)

 (gnu home)
 (guix channels)         

 (gnu services)
 (gnu home services)
 (gnu home services ssh)
 (gnu home services guix)
 (gnu home services gnupg)
 (gnu home services shells)
 (gnu home services desktop)
 (gnu home services shepherd)
 
 (gnu packages bash)
 (gnu packages base)
 (gnu packages emacs)
 (gnu packages emacs-xyz)
 (gnu packages shellutils)
 (gnu packages gnuzilla)
 (gnu packages web-browsers)
 (gnu packages screen)
 (gnu packages terminals)
 (gnu packages vim)
 (gnu packages admin)
 (gnu packages tmux)
 (gnu packages gnome)
 (gnu packages polkit)
 (gnu packages compression)
 (gnu packages curl)
 (gnu packages version-control)
 (gnu packages ssh)
 (gnu packages image-viewers)
 (gnu packages pulseaudio)
 (gnu packages networking)
 (gnu packages bittorrent)
 (gnu packages rsync)
 (gnu packages video)
 (guix gexp)
 (guix inferior)
 
 (gnu packages window-management)
 (gnu packages xdisorg)      
 (gnu packages fonts)

 (gnu packages image)      
 (gnu packages music)      
 (gnu packages linux)      

 (gnu packages gl)

 (gnu packages qt)
 (gnu packages uml)
 (gnu packages web)
 (gnu packages python)
 (gnu packages file)
 (gnu packages gnupg)
 (gnu packages tree-sitter)
 (gnu packages password-utils)
 (gnu packages rust-apps)
 (gnu packages pdf)

 (gnu packages man)
 (gnu packages glib)
 (gnu packages freedesktop)
 (gnu packages emulators)
 (gnu packages java)
 
 (nongnu packages mozilla)
 (nongnu packages chrome)
 (nongnu packages gradle)

 (my-packages claude-code)
 (my-packages governor)
 (my-packages kotlin-lsp)
 (my-packages kotlin-ts-mode)
 (my-scripts set-wallpaper)

 (guix packages)
 (guix build-system pyproject)
 ((guix licenses) #:prefix license:)
 (gnu packages check)
 (gnu packages python-web)
 (gnu packages python-build)

 (gnu services mcron)
 (gnu home services mcron))

(define my-emacs-packages
  (list
   emacs-pgtk
   emacs-use-package
   emacs-dumb-jump
   emacs-doom-themes
   emacs-doom-modeline
   emacs-all-the-icons
   emacs-almost-mono-themes
   emacs-tao-theme
   emacs-ef-themes
   emacs-vertico
   emacs-orderless
   emacs-marginalia
   emacs-consult
   emacs-embark
   emacs-corfu
   emacs-org-roam
   emacs-consult-org-roam
   emacs-org-journal
   emacs-magit
   emacs-flymake-flycheck
   emacs-eglot
   emacs-eldoc-box
   emacs-smartparens
   emacs-yasnippet
   emacs-yasnippet-snippets
   emacs-plantuml-mode
   emacs-kotlin-ts-mode
   emacs-jsdoc
   emacs-evil
   emacs-evil-smartparens
   emacs-evil-leader
   emacs-evil-commentary
   emacs-evil-org
   emacs-envrc

   ;; Guix development
   emacs-guix
   emacs-flycheck-guile
   emacs-geiser
   emacs-geiser-guile

   emacs-direnv
   
   ;; Treesitter Grammars
   tree-sitter-yaml
   tree-sitter-python
   tree-sitter-go
   tree-sitter-javascript
   tree-sitter-typescript
   tree-sitter-json
   tree-sitter-bash
   tree-sitter-rust
   ;; master, no el 0.3.8 de Guix: las queries de kotlin-ts-mode no casan
   ;; con el tag y Emacs desactiva el resaltado de cadenas y constantes.
   tree-sitter-kotlin-next))

(define my-font-packages
  (list font-awesome
	font-dejavu             
	font-google-noto
	font-cica
	font-google-noto-sans-cjk
	font-google-noto-serif-cjk
	font-google-noto-emoji))

(define my-dev-packages
  (list gnu-make
	man-pages
	man-pages-posix
	direnv
	claude-code
	git

	;; Kotlin: el LSP arranca con su propia JVM, pero openjdk:jdk y gradle
	;; hacen falta para compilar y para que el servidor importe el proyecto.
	kotlin-lsp
	gradle
	(list openjdk "jdk")))

(define my-utils-packages
  (list
   rsync
   p7zip
   rtorrent
   nautilus
   imv
   ripgrep
   jq
   pavucontrol
   strace
   file
   vim
   tmux
   htop  
   curl
   git
   openssh
   zathura
   zathura-pdf-mupdf
   unzip
   random-wallpaper))

(define my-wm-packages
  (list
   sway
   kanshi
   swaylock
   swayidle
   waybar      
   wofi
   wl-clipboard
   foot
   grim))

(define my-icons-packages
  (list
   hicolor-icon-theme
   adwaita-icon-theme))

(define my-other-packages
  (list
   vlc

   xeyes
   google-chrome-stable

   mesa 
   pipewire
   wireplumber
   
   playerctl     
   brightnessctl 
   
   polkit-gnome
   network-manager-applet
   blueman
   gnome-themes-extra      
   gsettings-desktop-schemas
   
   gnupg
   password-store
   pinentry-gnome3))

(define my-xdg-packages
  (list dbus
	xdg-desktop-portal
	xdg-desktop-portal-wlr
	xdg-desktop-portal-gtk
	slurp))

(define my-games-packages
  (list bsnes))

(define guix-emacs-config
  (mixed-text-file "guix-config.el"
		   ";; This file is generated by Guix. Do not edit.\n"
		   
		   ;; Disable 'ensure' because we cannot write to the store
		   "(setq use-package-always-ensure nil)\n"
		   
		   ;; Define the path to PlantUML Jar (Magic happens here!)
		   "(defvar guix-plantuml-jar-path \"" 
		   (file-append plantuml "/share/java/plantuml.jar") 
		   "\")\n"))

;; Descargador de wallpapers: la fuente vive en este mismo repo, así que
;; `local-file' evita mantener una copia sincronizada en ~/guix-packages.
;; pyproject-build-system envuelve bin/wallpaper-downloader con GUIX_PYTHONPATH,
;; de modo que arrastra su propio `requests' sin depender del profile.
(define wallpaper-downloader
  (package
    (name "wallpaper-downloader")
    (version "0.1.0")
    (source (local-file "scripts/wallpaper-downloader" #:recursive? #t
                        #:select? (lambda (file stat)
                                    (not (member (basename file)
                                                 '("test_output" ".direnv"
                                                   ".pytest_cache" ".ruff_cache"
                                                   "__pycache__"))))))
    (build-system pyproject-build-system)
    (propagated-inputs (list python-requests))
    (native-inputs (list python-setuptools python-wheel python-pytest))
    (home-page "https://wallhaven.cc")
    (synopsis "Descarga wallpapers 4K desde la API de Wallhaven")
    (description "Cliente de línea de comandos que descarga wallpapers desde la
API de Wallhaven a un directorio local, omitiendo los que ya existen.")
    (license license:gpl3+)))

(define random-wallpaper-lock
  (program-file
   "random-wallpaper-lock"
   #~(begin
       (use-modules (ice-9 popen)   
                    (ice-9 rdelim)  
                    (ice-9 ftw)     
                    (ice-9 match)
                    (srfi srfi-1)   
                    (srfi srfi-26)) 

       (define swaymsg  #$(file-append sway "/bin/swaymsg"))
       (define swaylock #$(file-append swaylock "/bin/swaylock"))
       (define jq       #$(file-append jq "/bin/jq"))
       (define bash     #$(file-append bash "/bin/bash"))

       (define (get-outputs)
         (let* ((cmd (string-join (list swaymsg "-t get_outputs |" jq "-r '.[].name'") " "))
                (port (open-pipe* OPEN_READ bash "-c" cmd)))
           (let loop ((line (read-line port)) (acc '()))
             (if (eof-object? line)
                 (begin (close-pipe port) (reverse acc))
                 (loop (read-line port) (cons line acc))))))

       (define (get-wallpapers dir)
         (if (file-exists? dir)
             (let ((files (scandir dir (lambda (f) 
                                         ;; Filter out "." and ".." and hidden files
                                         (not (string-prefix? "." f))))))
               (if files
                   (map (lambda (f) (string-append dir "/" f)) files)
                   '()))
             '()))

       (define (pick-random lst)
         (let ((state (random-state-from-platform)))
           (list-ref lst (random (length lst) state))))

       (define (ensure-dir dir)
         (unless (file-exists? dir)
           (mkdir dir #o755)))

       (let* ((home (getenv "HOME"))
              (wall-dir (string-append home "/images/wallpapers/4k"))
              (log-dir (string-append home "/.local/state"))
              (outputs (get-outputs))
              (wallpapers (get-wallpapers wall-dir)))

         (ensure-dir (string-append home "/.local"))
         (ensure-dir log-dir)

         (with-output-to-port (open-file (string-append log-dir "/random-wallpaper-lock.log") "a")
           (lambda ()
             (display (string-append "Locking at " (strftime "%c" (localtime (current-time))) "\n"))
             
             (cond
              ((null? wallpapers)
               (display "WARNING: No wallpapers found. Using black fallback.\n")
               (force-output)
               (execl swaylock "swaylock" "-f" "-c" "000000"))

              (else
               (let ((args (fold (lambda (output acc)
                                   (let ((wp (pick-random wallpapers)))
                                     (format #t "Output: ~a -> ~a\n" output wp)
                                     (cons* "-i" (string-append output ":" wp) acc)))
                                 '()
                                 outputs)))

                 (force-output)
                 (apply execl swaylock "swaylock" "-f" args))))))))))

(define my-swayidle-service
  (service home-shepherd-service-type
           (home-shepherd-configuration
            (services
             (list (shepherd-service
                    (provision '(swayidle))
                    (requirement '()) 
		    (auto-start? #f)
                    (documentation "Idle manager for Sway")
                    (start #~(make-forkexec-constructor
                              (list #$(file-append bash "/bin/bash") "-c"
                                    (string-join 
                                     (list 
                                      ;; 1. Environment Setup
                                      ;; We find the socket dynamically because Shepherd doesn't know it.
                                      "export SWAYSOCK=$(find /run/user/$(id -u) -name 'sway-ipc.*.sock' -print -quit);"
                                      "export WAYLAND_DISPLAY=${WAYLAND_DISPLAY:-wayland-1};"
                                      
                                      ;; 2. Start swayidle
                                      ;; We use 'exec' so swayidle takes over the bash PID.
                                      (string-append "exec " #$(file-append swayidle "/bin/swayidle") " -w")
                                      
                                      ;; 3. Arguments
                                      ;; timeout 300: Lock Screen
                                      "timeout 300" #$random-wallpaper-lock
                                      
                                      ;; timeout 600: Screen Off
                                      ;; Note: We wrap the command in single quotes '...' so swayidle sees it as one arg.
                                      "timeout 600" (string-append "'" #$(file-append sway "/bin/swaymsg") " \"output * dpms off\"'")
                                      
                                      ;; resume: Screen On
                                      "resume"      (string-append "'" #$(file-append sway "/bin/swaymsg") " \"output * dpms on\"'")
                                      
                                      ;; timeout 900: Suspend
                                      "timeout 900" (string-append "'" #$(file-append elogind "/bin/loginctl") " suspend'")
                                      
                                      ;; before-sleep: Lock Screen
                                      "before-sleep" #$random-wallpaper-lock)
                                     
                                     ;; Join all parts with a space
                                     " "))
                              
                              ;; 4. Log File
                              ;; The parenthesis is now CORRECTLY placed after this argument.
                              #:log-file (string-append (getenv "HOME") "/.local/share/shepherd/swayidle.log")))
                    (stop #~(make-kill-destructor))))))))

(home-environment
 (packages 
  (append 
   my-dev-packages
   my-wm-packages
   my-utils-packages
   my-font-packages
   my-icons-packages
   my-other-packages
   my-emacs-packages
   my-xdg-packages
   my-games-packages))
 
 (services
  (append
   (list
    my-swayidle-service

    (service home-dbus-service-type)

    (simple-service 'steam-tray-icon
                home-xdg-data-files-service-type
                (list (list "icons/hicolor/48x48/apps/steam_tray_mono.png"
                            (local-file "steam/steam_tray_mono.png"))))
    
    (simple-service 'pipewire-services
		    home-shepherd-service-type
		    (list
		     ;; Start Pipewire
		     (shepherd-service
		      (documentation "Pipewire multimedia server.")
		      (provision '(pipewire))
		      (start #~(make-forkexec-constructor
				(list #$(file-append pipewire "/bin/pipewire"))))
		      (stop #~(make-kill-destructor)))

		     ;; Start Wireplumber (Session Manager)
		     (shepherd-service
		      (documentation "Wireplumber session manager.")
		      (provision '(wireplumber))
		      (requirement '(pipewire))
		      (start #~(make-forkexec-constructor
				(list #$(file-append wireplumber "/bin/wireplumber"))))
		      (stop #~(make-kill-destructor)))

		     ;; Start Pipewire-Pulse
		     (shepherd-service
		      (documentation "Pipewire PulseAudio compatibility daemon.")
		      (provision '(pipewire-pulse))
		      (requirement '(pipewire))
		      (start #~(make-forkexec-constructor
				(list #$(file-append pipewire "/bin/pipewire-pulse"))))
		      (stop #~(make-kill-destructor)))))
    
    (service home-mcron-service-type
	     (home-mcron-configuration
	      (jobs
	       (list
		#~(job
		   '(next-minute (range 0 60 15)) 
		   #$random-wallpaper-script
		   "random-wallpaper-job")
		#~(job
		   '(next-hour)
		   (string-append
		    ;; el script no crea el directorio destino
		    "mkdir -p " #$(string-append (getenv "HOME") "/images/wallpapers/4k")
		    " && "
		    #$(file-append wallpaper-downloader "/bin/wallpaper-downloader")
		    ;; el script concatena output-path + nombre: la barra final importa
		    " --output-path " #$(string-append (getenv "HOME")
						       "/images/wallpapers/4k/"))
		   "wallpaper-downloader-job")))))

    (service home-bash-service-type
	     (home-bash-configuration
	      (guix-defaults? #t)
	      (aliases
               '(("warp-on"     . "(cd $HOME/Projects/warp; guix shell --substitute-urls='https://ci.guix.gnu.org https://bordeaux.guix.gnu.org' wireguard-tools openresolv -- sudo wg-quick up ./wgcf-profile.conf)")
                 ("warp-off"    . "(cd $HOME/Projects/warp; guix shell --substitute-urls='https://ci.guix.gnu.org https://bordeaux.guix.gnu.org' wireguard-tools openresolv -- sudo wg-quick down ./wgcf-profile.conf)")
                 ("warp-status" . "(cd $HOME/Projects/warp; guix shell --substitute-urls='https://ci.guix.gnu.org https://bordeaux.guix.gnu.org' wireguard-tools openresolv -- sudo wg show)")
		 ("audio-output" . "$HOME/.local/bin/audio-output-switch")
		 ("guix-system-update" . "nice -n 20 sudo guix pull && nice -n 20 sudo guix system reconfigure /etc/config.scm")
		 ("guix-home-update" . "nice -n 20 guix pull && nice -n 20 guix home reconfigure $HOME/.config/guix-home/home-config.scm")))
	      (bashrc 
	       (list 
		(plain-file "direnv-setup"
                        "eval \"$(direnv hook bash)\"")
		(plain-file "claude-code-setup"
			    (string-append
			     "export DISABLE_AUTOUPDATER=1\n"
			     ;; Claude revisa su ruta nativa ~/.local/bin/claude al
			     ;; arrancar; la apuntamos al wrapper de Guix para callar
			     ;; los avisos del 'doctor' sin que se autogestione.
			     "if [ ! -L \"$HOME/.local/bin/claude\" ]; then\n"
			     "  mkdir -p \"$HOME/.local/bin\"\n"
			     "  ln -sf \"$HOME/.guix-home/profile/bin/claude\" \"$HOME/.local/bin/claude\"\n"
			     "fi\n"))
		(plain-file "gpg-agent-setup" 
			    (string-append
			     "export GPG_TTY=$(tty)\n"
			     "gpg-connect-agent updatestartuptty /bye >/dev/null 2>&1\n"))))))

    (service home-gpg-agent-service-type
	     (home-gpg-agent-configuration
	      (pinentry-program 
	       (file-append pinentry-gnome3 "/bin/pinentry"))
	      
	      (default-cache-ttl 7200)
	      (max-cache-ttl 7200)  
	      
	      (ssh-support? #t)
	      
	      (extra-content "no-grab\n")))

    (service home-openssh-service-type
	     (home-openssh-configuration
	     (hosts
	       (list
		(openssh-host
		 (name "rpi 192.168.100.17")
		 (host-name "192.168.100.17")
		 (user "hector")
		 (identity-file "~/.ssh/id_rpi"))))))

    (simple-service 'guix-emacs-config
		    home-files-service-type
		    (list `(".emacs.d/guix-config.el" ,guix-emacs-config)))

    ;; Registra el plugin Governor en ~/.claude/settings.json apuntando al
    ;; marketplace del store.  Idempotente: se re-ejecuta en cada reconfigure
    ;; para actualizar la ruta del store cuando cambia la versión de governor.
    (simple-service 'governor-claude-plugin
		    home-activation-service-type
		    #~(system*
		       #$(file-append python "/bin/python3")
		       #$(local-file "scripts/governor-setup.py")
		       #$(file-append governor "/share/governor")))

    (simple-service 'wayland-env-vars-service
		    home-environment-variables-service-type
		    `(("GTK_THEME" . "Adwaita:dark")
		      ("GDK_BACKEND" . "wayland")
		      ("MOZ_ENABLE_WAYLAND" . "1")      
		      ("XDG_CURRENT_DESKTOP" . "sway")  
		      ("XDG_SESSION_TYPE" . "wayland")
		      ("LIBVA_DRIVER_NAME" . "radeonsi")
		      ("RADV_PERFTEST" . "aco")
		      ("mesa_glthread" . "true")
		      ("WLR_RENDERER" . "vulkan")
		      ("vblank_mode" . "0")
		      ("MESA_LOADER_DRIVER_OVERRIDE" . "radeonsi")))

    (simple-service 'dotfiles
		    home-files-service-type
		    (list 
		     `(".rtorrent.rc" ,(local-file "rtorrent/rtorrent.rc"))
		     `(".local/share/applications/google-chrome.desktop" ,(local-file "chrome/google-chrome-vulkan.desktop"))
		     `(".local/share/applications/steam-guix.desktop" ,(local-file "steam/steam.desktop"))
		     `(".local/share/applications/retroarch.desktop" ,(local-file "retroarch/retroarch.desktop"))
		     `(".local/share/applications/audio-output-switch.desktop" ,(local-file "scripts/audio-output-switch.desktop"))
		     `(".config/zathura/zathurarc" ,(local-file "zathura/zathurarc"))
		     `(".config/xdg-desktop-portal/portals.conf" ,(local-file "xdg/portals.conf"))
		     `(".config/waybar/config" ,(local-file "waybar/config"))
		     `(".config/waybar/style.css" ,(local-file "waybar/style.css"))
		     `(".config/waybar/scripts/weather.sh" ,(local-file "waybar/scripts/weather.sh"))
		     `(".config/waybar/scripts/warp.sh" ,(local-file "waybar/scripts/warp.sh"))
		     `(".config/waybar/scripts/speedtest.sh" ,(local-file "waybar/scripts/speedtest.sh"))
		     `(".config/wofi/style.css" ,(local-file "wofi/style.css"))
		     `(".local/bin/audio-output-switch" ,(local-file "scripts/audio-output-switch.sh" #:recursive? #t))
		     `(".tmux.conf" ,(local-file "tmux/tmux.conf"))
		     `(".emacs.d/init.el" ,(local-file "emacs/init.el"))
		     `(".config/foot/foot.ini" ,(local-file "foot/foot.ini"))
		     `(".config/sway/config" ,(local-file "sway/sway.conf"))
		     `(".config/kanshi/config" ,(local-file "kanshi/config"))
		     `(".gtkrc-2.0" ,(local-file "gtk/gtkrc-2.0"))
		     `(".config/gtk-3.0/settings.ini" ,(local-file "gtk/gtk3.ini"))
		     `(".config/gtk-4.0/settings.ini" ,(local-file "gtk/gtk4.ini"))))
    
    (service home-channels-service-type
	     (append
	      (list
	       (channel
		     (name 'nonguix)
		     (url "https://gitlab.com/nonguix/nonguix")
		     (introduction
		      (make-channel-introduction
		       "897c1a470da759236cc11798f4e0a5f7d4d59fbc"
		       (openpgp-fingerprint
			"2A39 3FFF 68F4 EF7A 3D29  12AF 6F51 20A0 22FB B2D5")))))
	      %default-channels))))))
